### ISSUE TITLE
Support private key auth

### ISSUE THREAD

**Issue by alexkreidler** [iqea-ai/duckdb-snowflake#6]
Looks like you have some code for private key and Oauth auth methods: https://github.com/iqea-ai/duckdb-snowflake/blob/67a895a7f36302f524ecdd0da14608bb68b95db5/src/include/snowflake_config.hpp#L9C49-L9C57

But it seems like theres no way to configure the extension to use it (eg via secrets).

It would be super useful especially for people who don't have Snowflake passwords (eg. access via SSO).

Thanks for a cool extension!

**Comment by alexkreidler** [comment]
Amazing news! I'm excited to try it.

I followed the instructions and put the extension in the folder, and got libadbc_driver_snowflake.so setup, but I got these errors:
```sh
[20:20:18] alexkreidler@mac /Users/alexkreidler/.duckdb/extensions/v1.4.0/osx_arm64
> duckdb
DuckDB v1.4.0 (Andium) b8a06e4a22
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SET allow_unsigned_extensions=true;
Invalid Input Error:
Cannot change allow_unsigned_extensions setting while database is running
D LOAD snowflake;
Invalid Input Error:
Failed to load 'snowflake', The file was built specifically for DuckDB version 'c8906e701e' and can only be loaded with that version of DuckDB. (this version of DuckDB is 'v1.4.0')
D
```

I may try building from source at that commit to see if it works but it would be great if the extension would also work for 1.4.0 and 1.4.1.

Thanks for your work on this!

**Comment by venkata-chikkam** [comment]
Ah sorry about that! My mistake - I pointed you to the old files from the `duckdb_1.3.2_test/` folder which were built for an older commit (`c8906e701e`). That's why you got the version mismatch error.

Here's where to get the correct v1.4.0 build:

**Download the pre-built extension here:**
https://github.com/iqea-ai/duckdb-snowflake/actions/runs/18791213504

Just grab the `snowflake-main-extension-osx_arm64` artifact (7.37 MB), extract it, and copy both `snowflake.duckdb_extension` and `libadbc_driver_snowflake.so` to `~/.duckdb/extensions/v1.4.0/osx_arm64/`

**One important thing:** You need to start DuckDB with the `-unsigned` flag since this is a community extension:

```bash
duckdb -unsigned
```

Then just:
```sql
LOAD snowflake;
```

The `allow_unsigned_extensions` setting won't work here because it can't be changed once DuckDB is already running - you have to use the `-unsigned` flag when you launch it.

This should work perfectly with your DuckDB v1.4.0! Let me know if you run into any issues. As for v1.4.1, I haven't tested it yet so I can't confirm support for that version.

Thanks for your patience!

**Comment by venkata-chikkam** [comment]
Thanks for testing it out so far! I have tested out all three issues you mentioned and the extension should be working fine, I think you may have some configuration issues that may need to be clarified.

## Key Pair Auth

I noticed in your code you created `my_keypair_secret` but then tried to attach with `airbyte_keypair_secret`. Assuming you're trying to connect with a correct secret, these fixes should help:

- Use `AUTH_TYPE 'key_pair'` (with the underscore)
- The parameter is just `PRIVATE_KEY`, not `PRIVATE_KEY_PATH`, and instead add the private key itself with the `-----BEGIN PRIVATE KEY-----` and `-----END PRIVATE KEY-----`
- Don't forget to add your public key to Snowflake with `ALTER USER myusername SET RSA_PUBLIC_KEY='...'`

## The "NameListToString" Error

This one's a DuckDB quirk. When you write `sf.ANALYTICS_DATABASE.information_schema.tables`, that's 4 parts, but DuckDB only handles 3. You need to put the database in your secret when you create it, then just use 3 parts in your query:

```sql
CREATE SECRET (... DATABASE 'ANALYTICS_DATABASE', ...);
SELECT * FROM sf.information_schema.tables;
```

## Slow Queries

Our tests ran in about 3-5 seconds. If you're seeing 9 minutes, you probably have a massive database with tons of tables. Try using `WHERE table_schema = 'posthog'` (exact match) instead of `LIKE`, or use `snowflake_query('SHOW TABLES', 'secret_name')` which tends to be faster, or enable pushdown.

Hope this helps! Let us know if you hit any other snags.

**Comment by venkata-chikkam** [comment]
@kyle-cheung Of course, I'd like to properly address this issue so I tested both password and keypair auth on my end and both work fine, so the extension and driver are good, I think the issue is in your secret configuration. Sorry about the `adbc_log_to_stderr` confusion, that setting isn't exposed in the current build. Can you share the output of this query instead (feel free to redact sensitive values)?

`SELECT * FROM duckdb_secrets() WHERE name = 'snowflake_keypair_unencrypted';`
That will show what DuckDB actually stored, most common issues are:
- Wrong account format (should be `account-region`, not the full URL)
- Private key path not absolute or not readable
- Missing grants on the warehouse/database for that user

**Comment by kyle-cheung** [comment]
I am trying a simpler account that only uses user and password auth:
```
name=my_keypair;type=snowflake;provider=config;serializable=true;scope;account=<hidden>;database=XOMETRY_MODELS;password=redacted;user=GREYBEAM_USER;warehouse=GREYBEAM_WH
```

Where `account` is set to just my account locator `SJDAS791-AJX7A` for example. However, it is still throwing the same error
```
D ATTACH '' AS sf_keypair (TYPE snowflake, SECRET my_keypair, READ_ONLY);
[DEBUG] GetCredentials: auth_type_str = ''
[DEBUG] auth_type_str is empty, using default PASSWORD auth
IO Error:
Failed to initialize database: Unknown ADBC error.
```

**Comment by venkata-chikkam** [comment]
@kyle-cheung The "Unknown ADBC error" usually means the ADBC driver failed without a detailed message. We tested password auth without the ADBC driver and saw the same error, so it's likely a driver loading issue.

Check that the ADBC driver version matches your Snowflake account setup. The same credentials should work with the Python ADBC driver manager. If they work there but not here, it's likely a driver loading or configuration issue. You can also try setting the driver path explicitly:

```bash
export SNOWFLAKE_ADBC_DRIVER_PATH="/path/to/libadbc_driver_snowflake.so"
```

**Comment by venkata-chikkam** [comment]
Good to hear you got it working, and thanks for testing it out patiently. The `AUTH_TYPE` case sensitivity issue is fixed. `AUTH_TYPE` parsing is now case-insensitive, so `'KEY_PAIR'`, `'key_pair'`, and other case variations all work.

The fix is available in the current version on `main` branch, or by installing the extension from the community repository: `INSTALL snowflake FROM community;`
